// -*- mode: kotlin -*-

/*
 * AUTOGENERATED BY glean_parser.  DO NOT EDIT.
 */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* ktlint-disable no-blank-line-before-rbrace */
@file:Suppress("PackageNaming", "MaxLineLength")
package org.mozilla.vrbrowser.GleanMetrics

import mozilla.components.service.glean.private.HistogramType // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.Lifetime // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.MemoryUnit // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.NoExtraKeys // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.NoReasonCodes // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.TimeUnit // ktlint-disable import-ordering no-unused-imports
import mozilla.components.service.glean.private.PingType // ktlint-disable import-ordering

internal object Pings {
    /**
     * This ping is sent at the end of a session (when Firefox Reality switches to the
     * background). We usually send search and UI control metrics at the end of a
     * session.
     */
    @get:JvmName("sessionEnd")
val sessionEnd: PingType<NoReasonCodes> =
        PingType<NoReasonCodes>(
            includeClientId = true,
            sendIfEmpty = false,
            name = "session-end",
            reasonCodes = listOf()
        )

}
